// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortariaRemotaAPI.Models.DataContext;

namespace PortariaRemotaAPI.Migrations
{
    [DbContext(typeof(KiperContext))]
    [Migration("20181217183109_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortariaRemotaAPI.Models.Apartamento", b =>
                {
                    b.Property<int>("ApartamentoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bloco");

                    b.Property<int>("Numero");

                    b.HasKey("ApartamentoId");

                    b.ToTable("Apartamentos");
                });

            modelBuilder.Entity("PortariaRemotaAPI.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pass")
                        .IsRequired();

                    b.Property<string>("User")
                        .IsRequired();

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new { LoginId = 1, Pass = "Kiper@2018", User = "Kiper" }
                    );
                });

            modelBuilder.Entity("PortariaRemotaAPI.Models.Morador", b =>
                {
                    b.Property<int>("MoradorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ApartamentoId");

                    b.Property<string>("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("Date");

                    b.Property<string>("EMail");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("MoradorId");

                    b.HasIndex("ApartamentoId");

                    b.ToTable("Moradores");
                });

            modelBuilder.Entity("PortariaRemotaAPI.Models.Morador", b =>
                {
                    b.HasOne("PortariaRemotaAPI.Models.Apartamento", "Apartamento")
                        .WithMany()
                        .HasForeignKey("ApartamentoId");
                });
#pragma warning restore 612, 618
        }
    }
}
